export const CLICK_ON_REQUEST = "CLICK_ON_REQUEST";
export const SET_POLYLINE_BETWEEN_MARKERS = "SET_POLYLINE_BETWEEN_MARKERS";
export const CHANGE_SELECT_REQUEST = "CHANGE_SELECT_REQUEST";
export const SET_ROW_ID = "SET_ROW_ID";
export const SET_SPLIT_PERCENTAGE = "SET_SPLIT_PERCENTAGE";

export const FROM_TYPE_MARKER = 'from';
export const TO_TYPE_MARKER = 'to';